#!/bin/bash

args=("$@")

yabai -m query --spaces --space "${args[0]}" > /dev/null 2>&1
if [ $? -eq 0 ] ; then
  yabai -m window --space "${args[0]}"
else
  echo "Space ${args[0]} does not exist. Creating..."
  yabai -m space --create > /dev/null 2>&1
  if [ $? -ne 0 ] ; then
    echo "Failed to create space ${args[0]}."
    exit 1
  fi
  echo "Space ${args[0]} created. Moving window..."
  yabai -m window --space "${args[0]}"
  echo "Window moved to space ${args[0]}."
fi
